version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: shop_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: shop
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - 3390:3306
      - 33900:33060
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: shop_redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf 
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
