version: "3.8"

services:
  mariadb:
    platform: linux/amd64
    image: mariadb:10.5.8
    container_name: shop_db
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: shop
      MARIADB_USER: username
      MARIADB_PASSWORD: password
    ports:
      - 3390:3306
      - 33900:33060
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: shop_redis
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf 
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
